DPDK_MEMCACHED_VERSION:=1.6.20
DPDK_MEMCACHED_SITE:="$(BR2_EXTERNAL_DPDK_GEM5_PATH)/package/dpdk_memcached/dpdk_memcached_src"
DPDK_MEMCACHED_CONF_ENV = ac_cv_prog_cc_c99='-std=gnu99'
DPDK_MEMCACHED_DEPENDENCIES = libevent
DPDK_MEMCACHED_SITE_METHOD:=local
DPDK_MEMCACHED_AUTORECONF = YES
DPDK_MEMCACHED_INSTALL_TARGET:=YES

$(eval $(cmake-package))